Update dev
sanger-tol/genomeassembly pull request #8
Opened 2022-11-17 16:47 UTC by ksenia-krasheninnikova

The changes from the following commits were merged:

[Template update for nf-core/tools version 2.5](https://github.com/sanger-tol/genomeassembly/pull/2/commits/372b36c76559e23dbf58e0eb70d341bfb036d5ef)
[Remove test.nf](https://github.com/sanger-tol/genomeassembly/pull/2/commits/21293c7f2ce8c44c861b79964cc0739df6fc4889)

Also, PR contains fix to the assets tests file and the workflow name update.

Changes were tested with
`nextflow run main.nf -profile test,singularity --outdir test -c conf/test.config`

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomeassembly/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-11-18 08:46 UTC, muffato requested changes
I noticed several changes that replace `sanger-tol/` with `nf-core/sanger-tol-`. `sanger-tol/` was fine !

2022-11-22 09:03 UTC, priyanka-surana commented
@ksenia-krasheninnikova Can you make the change to `nf-core/sanger-tol` to `sanger-tol`? I think this happened when template update was done.

2022-11-22 09:06 UTC, priyanka-surana commented on main.nf
> +include { SANGER_TOL_GENOMEASSEMBLY } from './workflows/sanger-tol-genomeassembly'
I think same goes for this. Revert back to the old convention.

2022-11-23 17:48 UTC, muffato reviewed
`lib/WorkflowSanger-tol-genomeassembly.groovy` can be renamed back as well (and the name of the class inside as well)

2022-11-23 17:48 UTC, muffato commented on workflows/genomeassembly.nf
> -WorkflowGenomeassembly.initialise(params, log)
Is that really needed ? I wonder if this line was failing because the file has been renamed

2022-11-29 15:40 UTC, priyanka-surana approved these changes
template changes mostly

2022-11-30 08:03 UTC, muffato approved these changes
I've run `black` and updated a few things like the copyright statement, the branding, etc.

2022-11-30 08:07 UTC, merged